//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class karyawan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public karyawan()
        {
            this.transaksis = new HashSet<transaksi>();
        }
    
        public int id_karyawan { get; set; }
        public Nullable<int> cabang_id { get; set; }
        public string kode_kar { get; set; }
        public string nama { get; set; }
        public bool aktif { get; set; }
        public string no_telp { get; set; }
    
        public virtual cabang cabang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaksi> transaksis { get; set; }
    }
}
