//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi
    {
        public int id { get; set; }
        public Nullable<int> id_kar { get; set; }
        public Nullable<short> tax_id { get; set; }
        public decimal total_pem { get; set; }
        public decimal price { get; set; }
        public double qty { get; set; }
    
        public virtual karyawan karyawan { get; set; }
        public virtual tax tax { get; set; }
    }
}
